version: "3.7"

x-node-image-version: &node-image-version 'node:16.6.1-buster'

x-node-image: &node-image
    image: *node-image-version
    user: node
    working_dir: /home/node/app

services:
  app:
    <<: *node-image
    volumes:
      - ./:/home/node/app
    ports:
      - 4200:4200
      - 9229:9229
      - 9876:9876
    command:
      - /bin/bash
      - -c
      - |
          yarn install
          yarn start
